name: trendy_movies
description: NA

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dartz: ^0.10.0
  dio: ^4.0.0

  #firebase
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  flutter_swipecards: ^0.2.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.14.3
  get: ^4.3.8

#hive db
  hive: ^2.0.4
  hive_flutter: ^1.1.0



  json_serializable: ^5.0.1
  json_annotation: ^4.1.0
  loggy: ^2.0.1
  flutter_loggy_dio: ^2.0.0+3
  retrofit: ^2.0.1
  colorize_text_avatar: ^1.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  flutter_translate: ^3.0.1
dependency_overrides:
  analyzer: ^2.3.0
  meta: 1.7.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  hive_generator: ^1.1.1
  retrofit_generator: ^2.0.1+1
  flutter_lints: ^1.0.4
  flutter_translate_gen: ^2.0.0
  dart_code_metrics: ^4.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/
