# This is a basic workflow to help you get started with Actions

name: Flutter CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
         channel: 'stable' # 'dev', 'alpha', default to: 'stable'
         
    # Get flutter dependencies.
      - run: flutter pub get
      #Generate code
      - run: flutter pub run build_runner build --delete-conflicting-outputs
    # Check for any formatting issues in the code.
#      - run: flutter format --set-exit-if-changed .
#
#    # Statically analyze the Dart code for any errors.
#      - run: flutter analyze .
#
#    # Run widget tests for our flutter project.
##      - run: flutter test
#
#      - name: Run a multi-line script
#        run: flutter pub run dart_code_metrics:metrics --reporter=github lib
#    # Build apk.
#      - run: flutter build apk
#          # Upload generated apk to the artifacts.
#      - uses: actions/upload-artifact@v1
#        with:
#          name: release-apk
#          path: build/app/outputs/apk/release/app-release.apk

  build_web:
    runs-on: ubuntu-latest
    needs: [ build]
    steps:
      - run: flutter config --enable-web
      - run: flutter build web --release
      - run: git --work-tree build/web add --all
      - run: git commit -m "Automatic deployment by github-actions"
      - run: git push origin HEAD:master --force

